### ISSUE TITLE
[1.8.0.0] Unable to load library 'LibOVRRT64_1.dll'

### ISSUE THREAD

**Issue by calvertdw** [jherico/jovr#11]
Where do I get this file? I downloaded the Oculus 1.8.0 SDK and it does not contain it, nor does the jovr JAR from mavenCentral. Will `LibOVR.lib` work?

**Comment by calvertdw** [comment]
I found it in `C:\Program Files\Oculus\Support\oculus-runtime`

**Comment by calvertdw** [comment]
Okay, posting this for future users. I downloaded the legacy runtime 0.8.0.0-beta from https://developer.oculus.com/downloads/package/oculus-runtime-for-windows/ and installed it, and that puts `LibOVRRT64_0_8.dll` in `C:\Windows\System32`. So I guess it appears @jherico is using the runtime provided by the standard Oculus Software installation in `C:\Program Files\Oculus\Support\oculus-runtime`.

**Comment by crramirez** [comment]
> So I guess it appears @jherico is using the runtime provided by the standard Oculus Software installation in C:\Program Files\Oculus\Support\oculus-runtime

Yes.  What problem did you have?
