### ISSUE TITLE
ovr.dll for 32bit jre

### ISSUE THREAD

**Issue by NuncObdurat** [jherico/jovr#5]
Hi jherico,

I recently switched from a 64 bit to 32 bit jre (1.8), and the old OculusVR.dll is no longer found.  I get the error below.

Unable to load library 'OculusVR': JNA native support (win32-x86/OculusVR.dll) not found in resource path.

Switching back to 64 bit solves the problem and everything works fine.

I saw your updates, and I believe the new library is the ovr.dll (correct me if I'm wrong), but it does not seem to be a valid library.  I get "This file is not a valid 32-bit or 64-bit Windows module" when running a dependency walker.  Maybe I'm doing something wrong? Any ideas?

Thanks,
Jason

**Comment by jherico** [comment]
At some point in the not too distant future I'm going to need to switch the OVR dll to the new SDK (0.6 / 0.7) which will mean no longer packaging a DLL inside the jar.

**Comment by NuncObdurat** [comment]
In the meantime, is there by chance a 32 bit version of the DLL for the 0.5 SDK?  Thanks again!

**Comment by jherico** [comment]
I don't have a lot of time to work on this.  However I'm looking at the jovr jar downloaded from [here](http://repo1.maven.org/maven2/org/saintandreas/jovr/0.4.4.0/) and it does appear to contain both the 64 and 32 bit DLLs for windows.  I'm not sure why you're getting the error.  You might have to tweak your native resources path.

**Comment by NuncObdurat** [comment]
Thanks! I didn't know about that jar.
